# Generated by Django 4.1.1 on 2022-10-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('sonali', 'Sonali'), ('rupali', 'Rupali'), ('bangladesh', 'Bangladesh'), ('world', 'World'), ('ific', 'IFIC')], default='sonali', max_length=10)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('deposit', 'Deposit'), ('fixed', 'Fixed')], default='current', max_length=10)),
                ('balance', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_is', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
